[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_sqlite", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "php82Extensions.gd", "php82Extensions.exif", "php82Extensions.fileinfo", "nodejs_20"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-req=ext-gd --ignore-platform-req=ext-exif", "npm install"]

[phases.build]
cmds = ["npm run build", "touch database/database.sqlite", "php artisan migrate --force"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
